### ISSUE TITLE
Bug when use optimized version for loading HSpell's dictionary files

### ISSUE THREAD

**Issue by naory159** [synhershko/HebMorph#51]
Hi

When I use optimized version for loading HSpell's dictionary files (Pass `false` in `HSpellLoader loader = new HSpellLoader(new File(HSpellLoader.getHspellPath()), false);`) I get that message:
`Exception in thread "main" java.lang.NullPointerException`.

`java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference`

It's happen when I call the function `parser.parse`.

Full Stack Trace:
`Exception in thread "main" java.lang.NullPointerException
    at com.code972.hebmorph.MorphData.getLemmas(MorphData.java:100)
    at com.code972.hebmorph.Lemmatizer.lemmatizeTolerant(Lemmatizer.java:154)
    at org.apache.lucene.analysis.hebrew.TokenFilters.HebrewLemmatizerTokenFilter.incrementToken(HebrewLemmatizerTokenFilter.java:99)
    at org.apache.lucene.analysis.hebrew.TokenFilters.AddSuffixTokenFilter.incrementToken(AddSuffixTokenFilter.java:42)
    at org.apache.lucene.analysis.CachingTokenFilter.fillCache(CachingTokenFilter.java:91)
    at org.apache.lucene.analysis.CachingTokenFilter.incrementToken(CachingTokenFilter.java:70)
    at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:223)
    at org.apache.lucene.queryparser.classic.QueryParserBase.newFieldQuery(QueryParserBase.java:480)
    at org.apache.lucene.queryparser.classic.QueryParserBase.getFieldQuery(QueryParserBase.java:472)
    at org.apache.lucene.queryparser.classic.QueryParserBase.handleBareTokenQuery(QueryParserBase.java:857)
    at org.apache.lucene.queryparser.classic.QueryParser.Term(QueryParser.java:348)
    at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:247)
    at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:171)
    at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:160)
    at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:118)
    at org.apache.lucene.queryparsers.HebrewQueryParser.parse(HebrewQueryParser.java:43)
    at test.beur.MySearchFiles.main(MySearchFiles.java:134)`

Hope the bug will fix fast!

**Comment by naory159** [comment]
There are expectations fix the problem?

**Comment by synhershko** [comment]
No, but we will be happy to accept a PR

**Comment by synhershko** [comment]
This doesn't seem to be a real issue, closing

**Comment by naory159** [comment]
Well, the bug still exist....
